[package]
name = "trilogy_save_editor"
version = "1.7.1"
authors = ["Karlitos"]
license = "CeCILL-2.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true

[dependencies]
# Macro
raw_ui_derive = { path = "raw_ui_derive" }
# Windows
winapi = { version = "0.3", features = ["consoleapi", "wincon"], default-features = false }
# Std-like
anyhow = "1.0"
derive_more = { version = "0.99", features = ["deref", "deref_mut", "from", "display"], default-features = false }
bitvec = { version = "0.22", features = ["std"], default-features = false }
indexmap = { version = "1.6", features = ["std"], default-features = false }
encoding_rs = { version = "0.8", default-features = false }
# Async
tokio = { version = "1.0", features = [
    "rt-multi-thread",
    "sync",
    "parking_lot",
    "macros",
    "fs",
    "io-util",
], default-features = false }
# Sync
# parking_lot = "0.11"
flume = { version = "0.10", features = ["async"], default-features = false }
# (De)Serializers
serde = { version = "1.0", features = ["derive"], default-features = false }
ron = { version = "0.6", features = ["indexmap"], default-features = false }
# Utils
crc = "2.0"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
zip = { version = "0.5", features = ["deflate-zlib"], default-features = false }
unicase = "2.6"
if_chain = "1.0"
# GUI
tinyfiledialogs = "3.8"
dirs = "3.0"
# Dear ImGui
imgui = { git = "https://github.com/imgui-rs/imgui-rs" }
imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs" }
imgui-wgpu = { git = "https://github.com/KarlitosVII/imgui-wgpu-rs" }
wgpu = "0.8"
winit = "0.24"
clipboard = "0.5"
